// Authored subtractive sound families. Stable slugs are part of the public preset API.
use super::Family;
use crate::Waveform::*;
pub(super) const FAMILIES: &[Family] = &[
    Family {
        id: "soft-sub",
        name: "Soft Sub",
        category: "Bass",
        waves: [Sine, Triangle],
        tune: 0,
        cutoff: 180.0,
        adsr: [0.01, 0.18, 0.75, 0.22],
        sub: 0.55,
        noise: 0.0,
        tag: "deep",
    },
    Family {
        id: "round-circuit",
        name: "Round Circuit",
        category: "Bass",
        waves: [Triangle, Saw],
        tune: 0,
        cutoff: 420.0,
        adsr: [0.015, 0.24, 0.58, 0.18],
        sub: 0.32,
        noise: 0.0,
        tag: "warm",
    },
    Family {
        id: "rubber-pulse",
        name: "Rubber Pulse",
        category: "Bass",
        waves: [Pulse, Saw],
        tune: 0,
        cutoff: 900.0,
        adsr: [0.005, 0.16, 0.38, 0.12],
        sub: 0.18,
        noise: 0.0,
        tag: "bouncy",
    },
    Family {
        id: "muted-reese",
        name: "Muted Reese",
        category: "Bass",
        waves: [Saw, Saw],
        tune: 0,
        cutoff: 1100.0,
        adsr: [0.02, 0.3, 0.48, 0.25],
        sub: 0.12,
        noise: 0.0,
        tag: "wide",
    },
    Family {
        id: "dark-triangle",
        name: "Dark Triangle",
        category: "Bass",
        waves: [Triangle, Triangle],
        tune: 12,
        cutoff: 650.0,
        adsr: [0.01, 0.4, 0.5, 0.3],
        sub: 0.25,
        noise: 0.0,
        tag: "mellow",
    },
    Family {
        id: "clipped-saw",
        name: "Clipped Saw",
        category: "Bass",
        waves: [Saw, Pulse],
        tune: 0,
        cutoff: 1500.0,
        adsr: [0.003, 0.1, 0.22, 0.09],
        sub: 0.1,
        noise: 0.0,
        tag: "gritty",
    },
    Family {
        id: "open-saw",
        name: "Open Saw",
        category: "Lead",
        waves: [Saw, Saw],
        tune: 0,
        cutoff: 5200.0,
        adsr: [0.02, 0.22, 0.72, 0.2],
        sub: 0.0,
        noise: 0.0,
        tag: "bright",
    },
    Family {
        id: "hollow-pulse",
        name: "Hollow Pulse",
        category: "Lead",
        waves: [Pulse, Pulse],
        tune: 0,
        cutoff: 2400.0,
        adsr: [0.01, 0.18, 0.6, 0.15],
        sub: 0.0,
        noise: 0.0,
        tag: "nasal",
    },
    Family {
        id: "soft-triangle",
        name: "Soft Triangle",
        category: "Lead",
        waves: [Triangle, Sine],
        tune: 12,
        cutoff: 3000.0,
        adsr: [0.04, 0.3, 0.65, 0.24],
        sub: 0.0,
        noise: 0.0,
        tag: "gentle",
    },
    Family {
        id: "detuned-edge",
        name: "Detuned Edge",
        category: "Lead",
        waves: [Saw, Pulse],
        tune: 7,
        cutoff: 6800.0,
        adsr: [0.015, 0.25, 0.58, 0.18],
        sub: 0.0,
        noise: 0.0,
        tag: "assertive",
    },
    Family {
        id: "narrow-reed",
        name: "Narrow Reed",
        category: "Lead",
        waves: [Pulse, Saw],
        tune: -12,
        cutoff: 1700.0,
        adsr: [0.03, 0.2, 0.55, 0.22],
        sub: 0.0,
        noise: 0.0,
        tag: "focused",
    },
    Family {
        id: "slow-ember",
        name: "Slow Ember",
        category: "Lead",
        waves: [Saw, Triangle],
        tune: 0,
        cutoff: 3600.0,
        adsr: [0.12, 0.35, 0.7, 0.4],
        sub: 0.0,
        noise: 0.0,
        tag: "expressive",
    },
    Family {
        id: "dusk-wash",
        name: "Dusk Wash",
        category: "Pad",
        waves: [Saw, Triangle],
        tune: 7,
        cutoff: 2400.0,
        adsr: [0.8, 1.5, 0.68, 2.4],
        sub: 0.05,
        noise: 0.0,
        tag: "warm",
    },
    Family {
        id: "soft-fifths",
        name: "Soft Fifths",
        category: "Pad",
        waves: [Triangle, Saw],
        tune: 7,
        cutoff: 3200.0,
        adsr: [1.1, 1.2, 0.62, 2.8],
        sub: 0.0,
        noise: 0.0,
        tag: "spacious",
    },
    Family {
        id: "low-haze",
        name: "Low Haze",
        category: "Pad",
        waves: [Sine, Triangle],
        tune: -12,
        cutoff: 900.0,
        adsr: [1.4, 1.6, 0.72, 3.2],
        sub: 0.24,
        noise: 0.0,
        tag: "dark",
    },
    Family {
        id: "pulse-cloud",
        name: "Pulse Cloud",
        category: "Pad",
        waves: [Pulse, Triangle],
        tune: 0,
        cutoff: 2100.0,
        adsr: [0.9, 1.3, 0.58, 2.6],
        sub: 0.0,
        noise: 0.0,
        tag: "mellow",
    },
    Family {
        id: "shimmer-bed",
        name: "Shimmer Bed",
        category: "Pad",
        waves: [Saw, Saw],
        tune: 12,
        cutoff: 4600.0,
        adsr: [1.6, 1.0, 0.55, 3.0],
        sub: 0.0,
        noise: 0.0,
        tag: "luminous",
    },
    Family {
        id: "muted-drift",
        name: "Muted Drift",
        category: "Pad",
        waves: [Triangle, Pulse],
        tune: 5,
        cutoff: 1500.0,
        adsr: [0.65, 1.8, 0.64, 2.2],
        sub: 0.08,
        noise: 0.0,
        tag: "introspective",
    },
    Family {
        id: "velvet-poly",
        name: "Velvet Poly",
        category: "Keys",
        waves: [Triangle, Saw],
        tune: 0,
        cutoff: 2600.0,
        adsr: [0.008, 0.45, 0.3, 0.55],
        sub: 0.0,
        noise: 0.0,
        tag: "rounded",
    },
    Family {
        id: "chord-bloom",
        name: "Chord Bloom",
        category: "Keys",
        waves: [Saw, Triangle],
        tune: 12,
        cutoff: 3800.0,
        adsr: [0.02, 0.6, 0.38, 0.7],
        sub: 0.0,
        noise: 0.0,
        tag: "lush",
    },
    Family {
        id: "muted-pulse-keys",
        name: "Muted Pulse Keys",
        category: "Keys",
        waves: [Pulse, Pulse],
        tune: 0,
        cutoff: 1900.0,
        adsr: [0.005, 0.28, 0.22, 0.32],
        sub: 0.0,
        noise: 0.0,
        tag: "percussive",
    },
    Family {
        id: "sine-top",
        name: "Sine Top",
        category: "Keys",
        waves: [Triangle, Sine],
        tune: 7,
        cutoff: 3000.0,
        adsr: [0.012, 0.38, 0.34, 0.5],
        sub: 0.0,
        noise: 0.0,
        tag: "clean",
    },
    Family {
        id: "dark-voicing",
        name: "Dark Voicing",
        category: "Keys",
        waves: [Saw, Saw],
        tune: -12,
        cutoff: 1400.0,
        adsr: [0.015, 0.7, 0.42, 0.65],
        sub: 0.06,
        noise: 0.0,
        tag: "smoky",
    },
    Family {
        id: "steady-poly",
        name: "Steady Poly",
        category: "Keys",
        waves: [Pulse, Saw],
        tune: 0,
        cutoff: 3300.0,
        adsr: [0.004, 0.12, 0.66, 0.16],
        sub: 0.0,
        noise: 0.0,
        tag: "steady",
    },
    Family {
        id: "bright-pick",
        name: "Bright Pick",
        category: "Pluck",
        waves: [Saw, Pulse],
        tune: 12,
        cutoff: 7200.0,
        adsr: [0.002, 0.24, 0.08, 0.28],
        sub: 0.0,
        noise: 0.0,
        tag: "crisp",
    },
    Family {
        id: "rounded-pluck",
        name: "Rounded Pluck",
        category: "Pluck",
        waves: [Triangle, Sine],
        tune: 0,
        cutoff: 2100.0,
        adsr: [0.004, 0.38, 0.1, 0.35],
        sub: 0.08,
        noise: 0.0,
        tag: "soft",
    },
    Family {
        id: "chime-pluck",
        name: "Chime Pluck",
        category: "Pluck",
        waves: [Pulse, Triangle],
        tune: 7,
        cutoff: 4500.0,
        adsr: [0.003, 0.18, 0.05, 0.32],
        sub: 0.0,
        noise: 0.0,
        tag: "nimble",
    },
    Family {
        id: "low-thumb",
        name: "Low Thumb",
        category: "Pluck",
        waves: [Triangle, Saw],
        tune: -12,
        cutoff: 800.0,
        adsr: [0.001, 0.28, 0.12, 0.2],
        sub: 0.22,
        noise: 0.0,
        tag: "woody",
    },
    Family {
        id: "filtered-pick",
        name: "Filtered Pick",
        category: "Pluck",
        waves: [Saw, Saw],
        tune: 5,
        cutoff: 3200.0,
        adsr: [0.006, 0.52, 0.16, 0.55],
        sub: 0.0,
        noise: 0.0,
        tag: "muted",
    },
    Family {
        id: "glass-pulse",
        name: "Glass Pulse",
        category: "Pluck",
        waves: [Pulse, Sine],
        tune: 12,
        cutoff: 6100.0,
        adsr: [0.002, 0.3, 0.06, 0.48],
        sub: 0.0,
        noise: 0.0,
        tag: "delicate",
    },
    Family {
        id: "sine-pair",
        name: "Sine Pair",
        category: "Bell",
        waves: [Sine, Sine],
        tune: 12,
        cutoff: 8000.0,
        adsr: [0.002, 1.2, 0.02, 1.8],
        sub: 0.0,
        noise: 0.0,
        tag: "pure",
    },
    Family {
        id: "triangle-tine",
        name: "Triangle Tine",
        category: "Bell",
        waves: [Triangle, Sine],
        tune: 19,
        cutoff: 6400.0,
        adsr: [0.003, 0.75, 0.03, 1.2],
        sub: 0.0,
        noise: 0.0,
        tag: "gentle",
    },
    Family {
        id: "pulse-glass",
        name: "Pulse Glass",
        category: "Bell",
        waves: [Pulse, Triangle],
        tune: 12,
        cutoff: 9200.0,
        adsr: [0.001, 0.55, 0.02, 1.0],
        sub: 0.0,
        noise: 0.0,
        tag: "bright",
    },
    Family {
        id: "soft-metal",
        name: "Soft Metal",
        category: "Bell",
        waves: [Sine, Triangle],
        tune: 7,
        cutoff: 5200.0,
        adsr: [0.004, 1.4, 0.04, 2.0],
        sub: 0.0,
        noise: 0.0,
        tag: "warm",
    },
    Family {
        id: "hollow-bell",
        name: "Hollow Bell",
        category: "Bell",
        waves: [Triangle, Triangle],
        tune: 19,
        cutoff: 3600.0,
        adsr: [0.003, 0.9, 0.03, 1.4],
        sub: 0.0,
        noise: 0.0,
        tag: "muted",
    },
    Family {
        id: "high-chime",
        name: "High Chime",
        category: "Bell",
        waves: [Sine, Pulse],
        tune: 24,
        cutoff: 10500.0,
        adsr: [0.001, 0.42, 0.01, 0.85],
        sub: 0.0,
        noise: 0.0,
        tag: "sharp",
    },
    Family {
        id: "sine-drawbars",
        name: "Sine Drawbars",
        category: "Organ",
        waves: [Sine, Sine],
        tune: 12,
        cutoff: 6500.0,
        adsr: [0.004, 0.08, 0.85, 0.1],
        sub: 0.0,
        noise: 0.0,
        tag: "pure",
    },
    Family {
        id: "soft-transistor",
        name: "Soft Transistor",
        category: "Organ",
        waves: [Triangle, Pulse],
        tune: 0,
        cutoff: 4200.0,
        adsr: [0.003, 0.1, 0.78, 0.12],
        sub: 0.0,
        noise: 0.0,
        tag: "mellow",
    },
    Family {
        id: "saw-chapel",
        name: "Saw Chapel",
        category: "Organ",
        waves: [Saw, Triangle],
        tune: 12,
        cutoff: 5200.0,
        adsr: [0.006, 0.14, 0.74, 0.16],
        sub: 0.0,
        noise: 0.0,
        tag: "full",
    },
    Family {
        id: "narrow-combo",
        name: "Narrow Combo",
        category: "Organ",
        waves: [Pulse, Pulse],
        tune: 0,
        cutoff: 2500.0,
        adsr: [0.002, 0.08, 0.68, 0.1],
        sub: 0.0,
        noise: 0.0,
        tag: "compact",
    },
    Family {
        id: "dark-sustainer",
        name: "Dark Sustainer",
        category: "Organ",
        waves: [Triangle, Saw],
        tune: -12,
        cutoff: 1800.0,
        adsr: [0.01, 0.22, 0.82, 0.2],
        sub: 0.1,
        noise: 0.0,
        tag: "subdued",
    },
    Family {
        id: "bright-rock",
        name: "Bright Rock",
        category: "Organ",
        waves: [Saw, Pulse],
        tune: 7,
        cutoff: 7800.0,
        adsr: [0.003, 0.1, 0.88, 0.12],
        sub: 0.0,
        noise: 0.0,
        tag: "biting",
    },
    Family {
        id: "soft-brass-stack",
        name: "Soft Brass Stack",
        category: "Brass",
        waves: [Saw, Pulse],
        tune: 0,
        cutoff: 2500.0,
        adsr: [0.06, 0.32, 0.72, 0.28],
        sub: 0.0,
        noise: 0.0,
        tag: "rounded",
    },
    Family {
        id: "short-stab",
        name: "Short Stab",
        category: "Brass",
        waves: [Saw, Saw],
        tune: 12,
        cutoff: 4800.0,
        adsr: [0.01, 0.22, 0.2, 0.18],
        sub: 0.0,
        noise: 0.0,
        tag: "punchy",
    },
    Family {
        id: "muted-section",
        name: "Muted Section",
        category: "Brass",
        waves: [Pulse, Saw],
        tune: 0,
        cutoff: 1700.0,
        adsr: [0.04, 0.25, 0.55, 0.25],
        sub: 0.0,
        noise: 0.0,
        tag: "mellow",
    },
    Family {
        id: "wide-fifth-brass",
        name: "Wide Fifth Brass",
        category: "Brass",
        waves: [Saw, Triangle],
        tune: 7,
        cutoff: 3600.0,
        adsr: [0.08, 0.4, 0.68, 0.35],
        sub: 0.0,
        noise: 0.0,
        tag: "broad",
    },
    Family {
        id: "synth-horn",
        name: "Synth Horn",
        category: "Brass",
        waves: [Pulse, Pulse],
        tune: 12,
        cutoff: 2900.0,
        adsr: [0.025, 0.3, 0.58, 0.24],
        sub: 0.0,
        noise: 0.0,
        tag: "focused",
    },
    Family {
        id: "low-brass-bed",
        name: "Low Brass Bed",
        category: "Brass",
        waves: [Triangle, Saw],
        tune: -12,
        cutoff: 1100.0,
        adsr: [0.07, 0.5, 0.7, 0.4],
        sub: 0.18,
        noise: 0.0,
        tag: "dark",
    },
    Family {
        id: "ensemble-saw",
        name: "Ensemble Saw",
        category: "Strings",
        waves: [Saw, Saw],
        tune: 0,
        cutoff: 4200.0,
        adsr: [0.35, 0.8, 0.72, 1.2],
        sub: 0.0,
        noise: 0.0,
        tag: "warm",
    },
    Family {
        id: "fifth-string-bed",
        name: "Fifth String Bed",
        category: "Strings",
        waves: [Saw, Triangle],
        tune: 7,
        cutoff: 3600.0,
        adsr: [0.5, 0.9, 0.68, 1.4],
        sub: 0.0,
        noise: 0.0,
        tag: "open",
    },
    Family {
        id: "soft-bow",
        name: "Soft Bow",
        category: "Strings",
        waves: [Pulse, Triangle],
        tune: 0,
        cutoff: 2400.0,
        adsr: [0.28, 0.65, 0.75, 1.1],
        sub: 0.0,
        noise: 0.0,
        tag: "mellow",
    },
    Family {
        id: "high-string-layer",
        name: "High String Layer",
        category: "Strings",
        waves: [Triangle, Saw],
        tune: 12,
        cutoff: 6100.0,
        adsr: [0.42, 0.8, 0.64, 1.3],
        sub: 0.0,
        noise: 0.0,
        tag: "airy",
    },
    Family {
        id: "low-cello-color",
        name: "Low Cello Color",
        category: "Strings",
        waves: [Saw, Triangle],
        tune: -12,
        cutoff: 1500.0,
        adsr: [0.2, 0.7, 0.72, 1.0],
        sub: 0.16,
        noise: 0.0,
        tag: "dark",
    },
    Family {
        id: "narrow-strings",
        name: "Narrow Strings",
        category: "Strings",
        waves: [Triangle, Pulse],
        tune: 5,
        cutoff: 2800.0,
        adsr: [0.6, 0.7, 0.65, 1.6],
        sub: 0.0,
        noise: 0.0,
        tag: "intimate",
    },
    Family {
        id: "filter-bloom",
        name: "Filter Bloom",
        category: "Motion",
        waves: [Saw, Triangle],
        tune: 0,
        cutoff: 4200.0,
        adsr: [0.3, 0.8, 0.68, 1.0],
        sub: 0.0,
        noise: 0.0,
        tag: "evolving",
    },
    Family {
        id: "pulse-tremor",
        name: "Pulse Tremor",
        category: "Motion",
        waves: [Pulse, Saw],
        tune: 7,
        cutoff: 3500.0,
        adsr: [0.08, 0.45, 0.6, 0.55],
        sub: 0.0,
        noise: 0.0,
        tag: "rhythmic",
    },
    Family {
        id: "pitch-drift",
        name: "Pitch Drift",
        category: "Motion",
        waves: [Triangle, Saw],
        tune: 0,
        cutoff: 2600.0,
        adsr: [0.18, 0.7, 0.62, 0.8],
        sub: 0.06,
        noise: 0.0,
        tag: "floating",
    },
    Family {
        id: "moving-fifth",
        name: "Moving Fifth",
        category: "Motion",
        waves: [Saw, Pulse],
        tune: 7,
        cutoff: 5200.0,
        adsr: [0.15, 0.55, 0.58, 0.75],
        sub: 0.0,
        noise: 0.0,
        tag: "rising",
    },
    Family {
        id: "resonant-sweep",
        name: "Resonant Sweep",
        category: "Motion",
        waves: [Triangle, Triangle],
        tune: 12,
        cutoff: 1800.0,
        adsr: [0.22, 0.65, 0.55, 0.9],
        sub: 0.0,
        noise: 0.0,
        tag: "liquid",
    },
    Family {
        id: "wide-slow-pulse",
        name: "Wide Slow Pulse",
        category: "Motion",
        waves: [Pulse, Pulse],
        tune: 0,
        cutoff: 3000.0,
        adsr: [0.4, 0.7, 0.64, 1.1],
        sub: 0.0,
        noise: 0.0,
        tag: "swaying",
    },
    Family {
        id: "filtered-air",
        name: "Filtered Air",
        category: "Texture",
        waves: [Sine, Triangle],
        tune: 0,
        cutoff: 7200.0,
        adsr: [0.18, 0.6, 0.28, 1.0],
        sub: 0.0,
        noise: 0.32,
        tag: "airy",
    },
    Family {
        id: "saw-dust",
        name: "Saw Dust",
        category: "Texture",
        waves: [Saw, Pulse],
        tune: 12,
        cutoff: 5600.0,
        adsr: [0.04, 0.45, 0.22, 0.7],
        sub: 0.0,
        noise: 0.12,
        tag: "grainy",
    },
    Family {
        id: "room-haze",
        name: "Room Haze",
        category: "Texture",
        waves: [Triangle, Sine],
        tune: -12,
        cutoff: 700.0,
        adsr: [0.6, 1.2, 0.42, 1.8],
        sub: 0.18,
        noise: 0.08,
        tag: "subdued",
    },
    Family {
        id: "pulse-veil",
        name: "Pulse Veil",
        category: "Texture",
        waves: [Pulse, Triangle],
        tune: 7,
        cutoff: 3900.0,
        adsr: [0.24, 0.7, 0.35, 1.1],
        sub: 0.0,
        noise: 0.18,
        tag: "hazy",
    },
    Family {
        id: "distant-saw",
        name: "Distant Saw",
        category: "Texture",
        waves: [Saw, Triangle],
        tune: 0,
        cutoff: 2800.0,
        adsr: [0.8, 1.1, 0.3, 2.0],
        sub: 0.0,
        noise: 0.03,
        tag: "distant",
    },
    Family {
        id: "breathy-band",
        name: "Breathy Band",
        category: "Texture",
        waves: [Triangle, Pulse],
        tune: 12,
        cutoff: 4800.0,
        adsr: [0.35, 0.9, 0.38, 1.4],
        sub: 0.0,
        noise: 0.24,
        tag: "soft",
    },
    Family {
        id: "low-sine-body",
        name: "Low Sine Body",
        category: "Percussive",
        waves: [Sine, Triangle],
        tune: -12,
        cutoff: 220.0,
        adsr: [0.001, 0.22, 0.02, 0.16],
        sub: 0.45,
        noise: 0.0,
        tag: "low",
    },
    Family {
        id: "snare-circuit",
        name: "Snare Circuit",
        category: "Percussive",
        waves: [Pulse, Triangle],
        tune: 7,
        cutoff: 2400.0,
        adsr: [0.001, 0.14, 0.03, 0.18],
        sub: 0.0,
        noise: 0.35,
        tag: "snappy",
    },
    Family {
        id: "noise-hat",
        name: "Noise Hat",
        category: "Percussive",
        waves: [Sine, Sine],
        tune: 0,
        cutoff: 10500.0,
        adsr: [0.001, 0.06, 0.0, 0.08],
        sub: 0.0,
        noise: 0.72,
        tag: "crisp",
    },
    Family {
        id: "triangle-tom",
        name: "Triangle Tom",
        category: "Percussive",
        waves: [Triangle, Sine],
        tune: -12,
        cutoff: 900.0,
        adsr: [0.002, 0.25, 0.03, 0.2],
        sub: 0.2,
        noise: 0.0,
        tag: "rounded",
    },
    Family {
        id: "pulse-click",
        name: "Pulse Click",
        category: "Percussive",
        waves: [Pulse, Pulse],
        tune: 0,
        cutoff: 6200.0,
        adsr: [0.001, 0.035, 0.0, 0.06],
        sub: 0.0,
        noise: 0.04,
        tag: "tight",
    },
    Family {
        id: "low-thump",
        name: "Low Thump",
        category: "Percussive",
        waves: [Triangle, Pulse],
        tune: -12,
        cutoff: 520.0,
        adsr: [0.001, 0.32, 0.02, 0.24],
        sub: 0.3,
        noise: 0.26,
        tag: "textured",
    },
];
